/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_jni_HelloWorld */

#ifndef _Included_main_java_jni_HelloWorld
#define _Included_main_java_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_jni_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_jni_HelloWorld_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
